// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ThiefBook_Reforge
{
    internal sealed partial class Vsix
    {
        public const string Id = "ThiefBook_Reforge.d7e4fda6-d879-4e87-90b6-5a8942852393";
        public const string Name = "ThiefBook_Reforge";
        public const string Description = @"An Extension to thief book in your status bar.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Frenqy";
        public const string Tags = "";
    }
}
