// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ThiefBook_Reforge
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ThiefBook_ReforgeString = "b6b974e5-feec-4eb0-8413-cd39fec22b2c";
        public static Guid ThiefBook_Reforge = new Guid(ThiefBook_ReforgeString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int HidePageCommand = 0x0100;
        public const int LastPageCommand = 0x0101;
        public const int NextPageCommand = 0x0110;
    }
}